version: '3.8'

services:
  db:

    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../django_api/.env

  api:
    build: ../
    restart: always
    volumes:
     - static_files:/app/static
    depends_on:
      - db
    env_file:
      - ../django_api/.env


  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/var/html/static/
      - media_files:/var/html/media

    depends_on:
      - api

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ../openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: ../django_api/openapi.yaml


  etl:
    image: elasticsearch:8.6.2 
    ports: 
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    depends_on:
      - db
    
  elastic_loader:
    build: ../etl
    restart: always
    depends_on:
      - db
      - etl
    env_file:
      - ../django_api/.env

volumes:
  static_files:
  media_files: