# Generated by Django 3.2 on 2022-11-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwork',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
    ]
