# Generated by Django 3.2 on 2023-06-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('DR', 'director'), ('WR', 'writer'), ('AC', 'actor')], max_length=2, null=True, verbose_name='role'),
        ),
    ]
