# Generated by Django 3.2 on 2023-06-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20230604_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('DR', 'director'), ('WR', 'writer'), ('AC', 'actor')], max_length=10, null=True, verbose_name='role'),
        ),
    ]
