# Generated by Django 3.2 on 2023-06-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('director', 'director'), ('writer', 'writer'), ('actor', 'actor')], max_length=10, null=True, verbose_name='role'),
        ),
    ]
