# Generated by Django 3.2 on 2023-06-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='personfilmwork',
            name='person_film_film_wo_6b9cac_idx',
        ),
    ]
